services:
  - type: web
    name: cmsmatrix-backend
    runtime: node
    rootDirectory: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production